version: '3'
services:

  authdb:
    container_name: authdb
    image: mysql:5.7
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: authdb
      MYSQL_USER: user
      MYSQL_PASSWORD: admin

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - authdb
      - redis

  redis:
    container_name: auth-service-cache
    image: "redis"
    hostname: redis
    ports:
      - "6379:6379"
    restart: always