server:
  port: 8081
spring:
  application:
    name: auth-service
  jackson:
      property-naming-strategy: SNAKE_CASE
  redis:
    master-url: redis
    master-port: 6379
    version-prefix: validation
    ttl: 180
  cache:
    type: redis
  datasource:
    url: jdbc:mysql://localhost:3307/authdb?allowPublicKeyRetrieval=true&characterEncoding=UTF-8&useSSL=false
    username: user
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
